version: "3.9"
services:
  gateway:
      container_name: nginx
      image: nginx:alpine
      build: ./gateway
      ports:
      - target: 80
        published: 80
      # volumes:
      # - type: bind
      #   source: ./gateway/nginx.conf
      #   target: /etc/nginx/nginx.conf
  frontend:
      container_name: garage-frontend
      image: garage-task-frontend:latest
      build: ./frontend
  backend:
      container_name: garage-backend
      image: garage-task-backend:latest
      build: ./backend
      environment:
        MYSQL_SERVER: ${MYSQL_SERVER}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    